### ISSUE TITLE
mikutter 3.5.2にてクラッシュする

### ISSUE THREAD

**Issue by trickart** [moguno/mikutter-tab-icon-size#1]
3.5.2(コミットID 9244031d9814bb176802e64d229b8bc642be6edd)にてtab-icon-sizeを入れたmikutterを起動すると画面が出た瞬間に落ちます。
<details>
<summary>.mikutter/tmp/mikutter-error</summary>
/opt/mikutter/core/plugin/gui/tablike.rb:83:in `set_icon': Unexpected class `NilClass'.
	 from /home/trick/.mikutter/plugin/mikutter-tab-icon-size/mikutter-tab-icon-size.rb:43:in `block (2 levels) in <top (required)>'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:49:in `block in call'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
	 from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
	 from /opt/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
	 from /opt/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
	 from /opt/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
	 from mikutter.rb:66:in `boot!'
	 from mikutter.rb:95:in `<main>'
/home/trick/.mikutter/plugin/mikutter-tab-icon-size/mikutter-tab-icon-size.rb:43:in `block (2 levels) in <top (required)>': Unexpected class `NilClass'. (RuntimeError)
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:49:in `block in call'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
	from /opt/mikutter/vendor/bundler/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
	from /opt/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
	from /opt/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
	from /opt/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
	from mikutter.rb:66:in `boot!'
	from mikutter.rb:95:in `<main>'
</details>

**Comment by moguno** [comment]
あー。すんません。そっち開発やめちゃったのでこっちを使ってもらえると嬉しいです。

https://github.com/moguno/mikutter-tab-hardpoint

**Comment by trickart** [comment]
了解です。
